version: '3.1'
services:
#  nginx:
#   container_name: v-nginx
#   image: nginx:1.13
#   restart: always
#   ports:
#   - 80:80
#   - 443:443
#   volumes:
#   - ./nginx/conf.d:/etc/nginx/conf.d
#    
#  mysql:
#   container_name: v-mysql
#   image: mysql/mysql-server:5.7
#   environment:
#    MYSQL_DATABASE: test
#    MYSQL_ROOT_PASSWORD: root
#    MYSQL_ROOT_HOST: '%'
#   ports:
#   - "3306:3306"
#   restart: always

  app:
    container_name: play-transaction
    image: timyangjava/play-transaction
    restart: always
    build: ./
    ports:
        - "8020:8020"
    depends_on:
        - redis-mono

  redis-mono:
    container_name: redis-mono
    image: redis:latest
    #environment:
    ports:
        - "6379:6379"
    restart: always
