spring:
  application:
    name: play-transaction
  jooq:
    sql-dialect: Postgres
  profiles:
    active: @activatedProperties@ #dev

server:
  port: 8020

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
