spring:
  application:
    name: play-transaction
  profiles:
    active: dev

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8020
  servlet:
    context-path: /play-transaction
  redis:
    host: 127.0.0.1
    port: 6379
