spring:
  redis:
    host: redis-mono
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.timyang.playground.transaction: "debug"

app:
  datasource:
    url: "jdbc:postgresql://postgresdb/market"
    username: "postgres"
    password: "secrect123"
    configuration:
      maximum-pool-size: 30
